sudo: required
language: python
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
deploy:
  provider: pypi
  user: MarkJisc
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    branch: develop
  password:
    secure: hCwCEfOt6LLNiwJty0pS+s4Gtvuyd1ZslV68DIWUXBowGF6lGshHj6LSltGi+RJBWeHOiqxLFtQ+FRZ7/q05zoaHKECQuL/BU4C2iTD64l1rmaw7/WAD+vSTkTYzr0EDbYkwYcKM0MDeS59eB21iniKtImte587/tXb4ecPgCgF7TQbcru1DbkidtLh9gmyr99GmFsIccGjuCKqV7q6kh+ht95fSCSWUDt1rqDhNevTfvyBPMmGkcBRA87MZKaVDzNwd+5Xk6TSfcHA5wXiuhK/Hc8zoYLEuXQnrgFM//UAvDcjndZfzD3cyN9AUbZ2GoHXLezLNhYB8mtqUEJ6Ywrocp7pa+wrWu8QnN0Gt5UPozMcZ+V14lzZyFNFJDoc5U6509wbDm2/f30gEoRaovoTkC9gzqFh15cekIKVi12eXcIBqTm+GhLG7XtkEhnZPGrO15iH1aCPFA/lJ8XWAG7ClJhymaJZsfJYCcmVidtAheukcrPQuFx5EzhBXzFfchH34bZe4qpstbThQUVDxzOqk6Aj9j3RzbD7X6jqwajmIP0hVKifIMZGylpo4carWelY8eEqAogMFFLmr/fxdhjOf2RpKqYszRNWdoRvrbMINVxV1p/pMDi32Bu1fOh/wHianU2Zw0BA8fis76nefTUg1lIHdgujffayRrnmYbEU=
