sudo: required
language: python
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
deploy:
  provider: pypi
  user: MarkJisc
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    branch: develop
  password:
    secure: ki1WB/tMOfyittuFGlzClXc0nQy0piDIYGmJF/yG1ZqQwlz8RIoYpMV8s3+10ib44a9bTmvBKnQ/6FFEw8A2JtGsPZmZhaxsMTfuCkE2D52Zq21EHDUX4GIiBAA0tvi0a7pbK2ZIuppD18utNry23vQ4k1DHan/injD1tGq/Qici7UB/PwEyW97Y+KIiJrjwb14pbPmMa4h69W+Lr+xH7xc1mNbCyfSSGjoFOJbupmAkoZqtzPwfgzztPDGwG9aErcOiySwT2/w89aExQrxh4Qlan/Y88QfsiQYGf+oCcZmSDObef7+FBumaehBucYzChbW2A1twWcOD2jhxEbN1rivV0cu8GEDFXFjoEHjDysglbpsgXcwVRwvjjxoPAbJ1+++dPc3fTgrWQP2hv2OV04mBT++M2zmRkd8lPGQEYPUFM4toj+s78uqokeLhqFkChNWE9oItcxG7fHF1tOUC7LbHZfHq7qDJj86uKGp0/nuofFsxm1Uj9pvsfBQRzDmPRCfCrl0qGpHuTZ3cZgbM7pXNQaftAxuHlcFsILO7wRtcJ9MaIWHiMVMUC5URNnHeHwknHTD2f44DXGpWejSm8lSRGo4FyavcdAVUxcycojE1nGHTwyHKz/I0oLIZFC9twsdpsqi0Yz9TdJp0EzOu9T+fRILnIi8hDGtZ860SDgs=
