sudo: required
language: python
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
deploy:
  provider: pypi
  user: MarkJisc
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    branch: develop
  password:
    secure: "SPPszK4nElnNsT0Xj+1r0Qy5/uR9nJcKCxdRHuJA6x+Yp8e7PJTwOw7uJn71gyNomZBQuUsRpZdvlO9HTEfz+t+tgybtv0AwQCUEobfWB2O5o3EdNGfCHeSNsCRlDTXqCUD2QaDoGwT595gNpZsGsJRWETMRW4k6du58DAIp4yHBMobIgA2uJQC24xFkcQJWMckuwHGTCVHhsu/suT8WKvq/jsFBar8BlbiCoUpFdfPYQ5URHVQubVX8yOElwkUVv+VGrITsSbVRMVMkQyURGIXhNdh/snbDcfx+qspE54bqkjvjAemp5KN8Nezy/5QvDjRcQnWBiLq/r5YCi8I6+OnFKvszDh5EHGyPSF2wF+I6FqeK3vLY25gMlHKQo+RfnBK5vvR1V/30fWcqhidZo69KAGNVn+X0bUrpC7r+oagKz9vzQ/KeLQUWAiNA47CTCcTHajWRxfbupgBG4H2Lu2NTvRrNAbnLQD294NYszMHWYL5jn0wBWAipzwg6xJuOm98CRPujLwPVr1XCdSbfiPCWCD0ci5IbMSIUmfRaVI5am0pA/c4/5CyCsNJ+xKQzNNcH/JG47iSp79JyoDCOPP2H28X5kbcWXuQjKy7A6ijWS9PD4befoUEcS/kFIJNVYReJIoJrXlukJNg+RwyYVlv50O2cKBMOz9/x6CiOJ7o="
