sudo: required
language: python
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
deploy:
  provider: pypi
  user: MarkJisc
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  on:
    branch: develop
  password:
    secure: dscQqWniLDP6wzoFXXJX+OzJAJveDed+9et6U2TalKel3lsPSej5oiWgpy7HVQYh0672XhtK3sAIbVdLjdIogzw7xBnRJpUhTIy39eSXqjP7iEutKSLW6gl9d9nJyiO2X8f1i4d5q7pYm3ry27XMmzTgGBwUcg2Pxb8bX6o+BgqKuFUgzZ0Ai+KWpdaTewUD0I/kCvnY1P1rTYi3kkJxminy2rdP2xiN8w3lswF6ZrtYme7k1f7wo+p6nahIIpZu4NQYl9jK/QYtBq8WOvAH//ZfizmUvc5kncRZiBbEu2JEBZyWgpwRFRCQYfknFf6dV5QB+SVWzu3TWfGoavoDDnwD83BeHzwYZ929nTAn0RTbw4qkRv3j4EMVSD+Z74JO3Cx36MGhSejN9DfcE9aRW/0lNjRwXKTOvc3X9bQnmmwgfjsH+8QWMF+LJUfo6O+CdWKvSLqbmv2HQO9NXIztVysCKef4yKDQFVOQ4Q83eETshDZICFsQAH2P+hk+ikGLz8LOqBECjNmbdJKExsFIjnJWAj2hOmiXHmBogjjx7r7nTUy9zHJRDHVd08bYd+hiXE6V7svl4ukr2ULkNoYjZUQUUB5sBe1tVu3DkXitFbgOIi9b9TwmWSIM9csk4QKizkshu2vkszugNBzgUOR+jErQ7azwu2UKtlFwD6GdmUk=
