sudo: required
language: python
python:
- '3.6'
install:
- make deps
script:
- make lint
- make test
deploy:
  provider: pypi
  user: "MarkJisc"
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi
  on:
    branch: develop
  password:
    secure: gja7qPfL7A3usnDdOG3s7xDljy+1Y378vpRV2bZa+Qt4U6p3Pgo8C8ZX1EndJr6CYguVV3tqNH7QsQG5iNw94M1dINm9e1EUOlbWywTkAESNgH9aYEQStGcjY4bKeWGrN37z8AgQFQ9Z7LhgV8tF5JRtKjuj8UzVN/PuLmLYwLmLnLG/ejPUBtwn6XYotqxVrwtE9QuKY5obV4+1uB9VzbcIGFEIhfKB4URW5aNwafIcaoBzm1TIeZqMHNl5SBDAUVkOvmKoJp5XxVpECJ3DqErj/9UiyKul6JkhC77GpJM9UlJUUljbEDrsTJGuX5jckPLraTLFsE6EASryp7H1bNyigbj0rZrp0n9JAYBOyUZIVFJwl/TK2DxF/C2dwZ7Hkdla48pA7FpvyFV9L+cA44GpPAoxTwb0iwsrSKKpIGosgIp9+yjScElIZioUUYilETXMvQMtcfydecoq6tNU4zOTXgEd9PHdGqgCUgUb7NqxtyjBSikh5mJacVIqR82+miYcEDrmTm7h45JeP3qDmElpAwdeXKZYkvy8/lCD71DF0ysIKYItdXY460VChOOEifSRiX6JirXyklLf2Ys1Me7Zlu2AXl/2IdJUSwKGy1Iw03oeX6uTCx0EZHA0LZROGgKCYGNI1gg4HGVLRUJv3BdJn4/14GXStkhYC7+zdY4=
